jtransc-gen-haxe/src/com/jtransc/gen/haxe/HaxeTarget.kt, jtransc-rt-core/src/com/jtransc/thread/JTranscThreading.java, jtransc-rt/src/java/lang/Thread.java
=> MultiThread

jtransc-rt/src/java/lang/Class.java, jtransc-rt/src/java/lang/jtransc/JTranscCoreReflection.java
I try write it, but not sure about my code, please, check it before apply.
=> Class.getGenericSuperclass

jtransc-main/test/big/BigTest.kt, jtransc-main/test/issues/issue146/IInterface.java, jtransc-main/test/issues/issue146/Impl_0.java, jtransc-main/test/issues/issue146/Impl_1.java, jtransc-main/test/issues/issue146/Impl_2.java, jtransc-main/test/issues/issue146/Impl_3.java, jtransc-main/test/issues/issue146/Issue146.java
=> Test for issue 146

jtransc-rt-core/src/com/jtransc/charset/JTranscCharBuffer.java, jtransc-rt-core/src/com/jtransc/charset/JTranscCharset.java, jtransc-rt-core/src/com/jtransc/charset/JTranscCharsetSingleByte.java, jtransc-rt-extended-charsets/src/com/jtransc/charset/charsets/JTranscCharsetShiftJIS.java, jtransc-rt/src/com/jtransc/charset/charsets/JTranscCharsetUTF16Base.java, jtransc-rt/src/com/jtransc/charset/charsets/JTranscCharsetUTF8.java
I check on my project all strings compare with java version, but anyway review it.
=> fix #138 StringBuffer problem

jtransc-gen-cpp/src/com/jtransc/gen/cpp/CppTarget.kt, jtransc-main/test/big/BigTest.kt
This may fix a compilnation problem, but I'm not sure if it is correct.
=> frem -> fmod

jtransc-core/src/com/jtransc/ast/AstTransformer.kt, jtransc-core/src/com/jtransc/ast/AstVisitor.kt, jtransc-core/src/com/jtransc/ast/ast_body.kt, jtransc-core/src/com/jtransc/ast/dependency/analyzer.kt, jtransc-core/src/com/jtransc/ast/feature/method/UndeterministicParameterEvaluationFeature.kt, jtransc-core/src/com/jtransc/ast/feature/program/LambdaProgramFeature.kt, jtransc-core/src/com/jtransc/gen/common/CommonGenerator.kt, jtransc-core/src/com/jtransc/plugin/reflection/MetaReflectionJTranscPlugin.kt, jtransc-gen-cpp/src/com/jtransc/gen/cpp/CppTarget.kt, jtransc-gen-cs/src/com/jtransc/gen/cs/CSharpTarget.kt, jtransc-gen-haxe/src/com/jtransc/gen/haxe/HaxeTarget.kt, jtransc-rt/resources/as3/JA_L.as, jtransc-rt/resources/cpp/Base.cpp, jtransc-rt/resources/cs/Base.cs, jtransc-rt/resources/d/Base.d, jtransc-rt/resources/dart/Base.dart, jtransc-rt/resources/hx/JA_B.hx, jtransc-rt/resources/hx/JA_C.hx, jtransc-rt/resources/hx/JA_D.hx, jtransc-rt/resources/hx/JA_F.hx, jtransc-rt/resources/hx/JA_I.hx, jtransc-rt/resources/hx/JA_J.hx, jtransc-rt/resources/hx/JA_L.hx, jtransc-rt/resources/hx/JA_S.hx, jtransc-rt/resources/hx/N.hx, jtransc-rt/resources/js/Base.js, jtransc-rt/resources/php/Base.php
This PR will try to fix https://github.com/jtransc/jtransc/issues/206
=> Try to use array literals on reflection plugin

jtransc-gen-php/src/com/jtransc/gen/php/PhpTarget.kt, jtransc-rt/src/java/lang/Runtime.java, jtransc-rt/src/java/lang/StringBuilder.java
Fixes compile error on PHP, AS3 and Dart.
=> Small fixes

README.md, appveyor.yml, build.gradle, gradle.properties, jtransc-main/test/JsTest.kt, jtransc-main/test/big/BigTest.kt, jtransc-main/test/issues/Issue105.java
Hopefully, this will also trigger appveyor (I have added the webhook already)
=> Added app-veyor badge

jtransc-core/src/com/jtransc/ast/ast.kt, jtransc-core/src/com/jtransc/ast/feature/method/GotosFeature.kt, jtransc-core/src/com/jtransc/ast/optimize/ast_optimize.kt, jtransc-core/src/com/jtransc/backend/AsmToAst.kt, jtransc-core/src/com/jtransc/backend/asm1/AsmToAst1.kt, jtransc-core/src/com/jtransc/backend/asm1/AsmToAstMethodBody1.kt, jtransc-core/src/com/jtransc/backend/asm2/AsmToAst2.kt, jtransc-gen-js/src/com/jtransc/gen/js/JsTarget.kt, jtransc-gradle-plugin/src/com/jtransc/gradle/JTranscGradleExtension.kt, jtransc-gradle-plugin/src/com/jtransc/gradle/tasks/AbstractJTranscGradleTask.kt, jtransc-main/test/HaxeTest.kt, jtransc-main/test/JsTest.kt, jtransc-main/test/_Base.kt, jtransc-main/test/issues/Issue219.java, jtransc-rt/resources/js/Base.js
Enable array bounchecking on direct JS target on debug builds
Fixes #219
=> Added option "optimize" & disable local inlining for now

jtransc-rt/resources/hx/JA_B.hx, jtransc-rt/resources/hx/JA_C.hx, jtransc-rt/resources/hx/JA_D.hx, jtransc-rt/resources/hx/JA_F.hx, jtransc-rt/resources/hx/JA_I.hx, jtransc-rt/resources/hx/JA_J.hx, jtransc-rt/resources/hx/JA_L.hx, jtransc-rt/resources/hx/JA_S.hx, jtransc-rt/resources/hx/N.hx
Yep. memcpy was my fault. And that is very likely the cause of random failures in travis.
https://github.com/jtransc/jtransc/blob/0c443d30af60f1fde4f95a8ec98ceaa909e5f66b/jtransc-rt/resources/hx/N.hx#L554
Replaced to memmove
=> Fix haxecpp travis

jtransc-core/src/com/jtransc/plugin/reflection/MetaReflectionJTranscPlugin.kt, jtransc-main/test/JsTest.kt, jtransc-rt-core/src/j/ProgramReflection.java
@soywiz Maybe it crazy, but works for Haxecpp =) Please, review why not working testNanoHelloWorldShouldReferenceGetMethods
=> split getAllClasses for fix OOM in 32bit

README.md
=> improve README for Win64

.travis.yml, README.md, includeCommon.gradle, jtransc-core/src/com/jtransc/plugin/service/ServiceLoaderJTranscPlugin.kt, jtransc-main/test/JsTest.kt, jtransc-main/test/android/AndroidTest8019.java, jtransc-main/test/big/BigTest.kt, jtransc-main/test/javatest/JacocoFilters.java, jtransc-main/test/javatest/misc/MiscTest.java, jtransc-main/test/jtransc/jtransc/nativ/JTranscJsNativeMixedTest.java, jtransc-main/test/jtransc/rt/test/JTranscCloneTest.java, jtransc-main/test/jtransc/rt/test/JTranscReflectionTest.java, jtransc-rt/src/java/util/ServiceLoader.java
=> Integrates with codecov.io

jtransc-gen-common-tests/build.gradle, jtransc-gen-common-tests/src/big/BigTest.kt, jtransc-gen-common-tests/src/javaxtest/sound/SimpleSoundTest.java, jtransc-gen-js/test/com/jtransc/gen/js/JsTest.kt, jtransc-rt/src/javax/sound/sampled/AudioFileFormat.java, jtransc-rt/src/javax/sound/sampled/AudioFormat.java, jtransc-rt/src/javax/sound/sampled/AudioInputStream.java, jtransc-rt/src/javax/sound/sampled/AudioSystem.java, jtransc-rt/src/javax/sound/sampled/Clip.java, jtransc-rt/src/javax/sound/sampled/Control.java, jtransc-rt/src/javax/sound/sampled/DataLine.java, jtransc-rt/src/javax/sound/sampled/Line.java, jtransc-rt/src/javax/sound/sampled/LineEvent.java, jtransc-rt/src/javax/sound/sampled/LineListener.java, jtransc-rt/src/javax/sound/sampled/Mixer.java, jtransc-rt/src/javax/sound/sampled/SourceDataLine.java, jtransc-rt/src/javax/sound/sampled/TargetDataLine.java
=> Added sound sampled related dummy classes

jtransc-gen-common-tests/build.gradle, jtransc-gen-common-tests/src/big/BigTest.kt, jtransc-gen-common-tests/src/javatest/net/ServerSocketTest.java, jtransc-gen-common-tests/src/javatest/utils/OptionalTest.java, jtransc-gen-js/test/com/jtransc/gen/js/JsTest.kt, jtransc-rt/src/java/net/DatagramPacket.java, jtransc-rt/src/java/net/DatagramSocket.java, jtransc-rt/src/java/net/InterfaceAddress.java, jtransc-rt/src/java/net/NetworkInterface.java, jtransc-rt/src/java/net/ProtocolFamily.java, jtransc-rt/src/java/net/ServerSocket.java, jtransc-rt/src/java/nio/channels/Channel.java, jtransc-rt/src/java/nio/channels/DatagramChannel.java, jtransc-rt/src/java/nio/channels/MembershipKey.java, jtransc-rt/src/java/nio/channels/MulticastChannel.java, jtransc-rt/src/java/nio/channels/Pipe.java, jtransc-rt/src/java/nio/channels/SelectableChannel.java, jtransc-rt/src/java/nio/channels/SelectionKey.java, jtransc-rt/src/java/nio/channels/Selector.java, jtransc-rt/src/java/nio/channels/ServerSocketChannel.java, jtransc-rt/src/java/nio/channels/SocketChannel.java, jtransc-rt/src/java/nio/channels/spi/AbstractSelectableChannel.java, jtransc-rt/src/java/nio/channels/spi/AbstractSelectionKey.java, jtransc-rt/src/java/nio/channels/spi/AbstractSelector.java, jtransc-rt/src/java/nio/channels/spi/SelectorProvider.java, jtransc-rt/src/java/util/Optional.java, jtransc-rt/src/java/util/function/Consumer.java
=> Add missing net related classes + java.util.Optional

jtransc-core/src/com/jtransc/ast/ast.kt, jtransc-core/src/com/jtransc/gen/common/CommonGenerator.kt, jtransc-core/test/com/jtransc/ast/AstKtTest.kt, jtransc-gen-as3/src/com/jtransc/gen/as3/As3Target.kt, jtransc-gen-cpp/src/com/jtransc/gen/cpp/CppTarget.kt, jtransc-gen-cs/src/com/jtransc/gen/cs/CSharpTarget.kt, jtransc-gen-d/src/com/jtransc/gen/d/DTarget.kt, jtransc-gen-dart/src/com.jtransc.gen.dart/DartTarget.kt, jtransc-gen-haxe/src/com/jtransc/gen/haxe/HaxeTarget.kt, jtransc-gen-js/src/com/jtransc/gen/js/JsTarget.kt, jtransc-gen-php/src/com/jtransc/gen/php/PhpTarget.kt
Added target + os to defines available to cond; made it open so targets can add custom defines
=> Support cond for annotations: JTranscAddLibraries, JTranscAddIncludes, JTranscAddDefines, JTranscAddImports

jtransc-gen-common-tests/src/jtransc/bug/JTranscBug244.java, jtransc-gen-haxe/src/com/jtransc/gen/haxe/HaxeTarget.kt, jtransc-rt/resources/cpp/Base.cpp, jtransc-rt/resources/cs/Base.cs, jtransc-rt/resources/d/Base.d, jtransc-rt/resources/dart/Base.dart, jtransc-rt/resources/hx/N.hx, jtransc-rt/resources/js/Base.js
=> long f = (long) Float.NaN

gradle.properties, jtransc-maven-plugin/example/pom.xml, jtransc-maven-plugin/resources/META-INF/maven/plugin.xml, jtransc-utils/src/com/jtransc/KotlinVersion.kt
What's relevant: this brings performance improvements in the IDE and generated bytecode:
https://blog.jetbrains.com/kotlin/2017/08/kotlin-1-1-4-is-out/
=> Updated kotlin to 1.1.4

README.md, jtransc-rt/src/java/util/concurrent/ScheduledThreadPoolExecutor.java
Also need support synchronized ASAP
=> fix scheduled submit

jtransc-core/src/com/jtransc/gen/common/CommonGenerator.kt, jtransc-gen-common-tests/src/big/ThreadTest.java, jtransc-gen-common-tests/src/javatest/misc/Misc2Test.java, jtransc-gen-common-tests/src/jtransc/ref/MethodBodyReferencesTest.java, jtransc-gen-common-tests/src/jtransc/rt/test/ProxyTest.java, jtransc-gen-cpp/src/com/jtransc/gen/cpp/CppTarget.kt, jtransc-gen-cs/src/com/jtransc/gen/cs/CSharpTarget.kt, jtransc-gen-dart/src/com.jtransc.gen.dart/DartTarget.kt, jtransc-gen-haxe/src/com/jtransc/gen/haxe/HaxeTarget.kt, jtransc-gen-js/src/com/jtransc/gen/js/JsTarget.kt, jtransc-gen-js/test/com/jtransc/gen/js/JsTest.kt, jtransc-gen-php/src/com/jtransc/gen/php/PhpTarget.kt, jtransc-rt-core/resources/js/SimdPolyfill.js, jtransc-rt-core/src/com/jtransc/JTranscArrays.java, jtransc-rt-core/src/com/jtransc/JTranscWrapped.java, jtransc-rt-core/src/com/jtransc/ds/FastStringMap.java, jtransc-rt-core/src/com/jtransc/io/JTranscConsole.java, jtransc-rt-core/src/com/jtransc/text/JTranscStringTools.java, jtransc-rt/resources/js/Base.js, jtransc-rt/src/java/lang/Object.java, jtransc-rt/src/java/lang/Runtime.java, jtransc-rt/src/java/lang/Thread.java, jtransc-rt/src/java/nio/channels/AsynchronousServerSocketChannel.java, jtransc-rt/src/java/nio/channels/AsynchronousSocketChannel.java, jtransc-rt/src/java/util/concurrent/Semaphore.java, jtransc-rt/src/javax/script/jtransc/impl/JSJtranscScriptEngine.java
We need to propagate an object between calls to determine in which thread we are.
=> [JS] Implement Thread capabilities in JS

jtransc-gradle-plugin/build.gradle
Related to https://github.com/jtransc/jtransc/issues/302
=> build.gradle: Update website
